# Use an official PHP runtime as a base image
FROM php:8.1.2-apache

# Set the working directory in the container
WORKDIR /var/www/html

# Copy the PHP files from your host to the container
COPY . /var/www/html
